%%%%%% Functional box-plot
function [stat_grp] = Functional_BoxPlot(data_long,X_name,Y_name,...
    Sup_title,Sub_title,X_lab,Y_lab)

stat_grp = grpstats(data_long,X_name,{'min',...
    @(data_long_boxplot)  prctile(data_long_boxplot,1),...
    @(data_long_boxplot)  prctile(data_long_boxplot,5),...
    @(data_long_boxplot)  prctile(data_long_boxplot,25),...
    'mean','median',...
    @(data_long_boxplot)  prctile(data_long_boxplot,75),...
    @(data_long_boxplot)  prctile(data_long_boxplot,95),...
    @(data_long_boxplot)  prctile(data_long_boxplot,99),...
    'max','iqr','sem','std'},...
    'DataVars',{Y_name},...
    'VarNames',{'Hour','GroupCount','min','q1','q5','q25','mean','median',...
    'q75','q95','q99','max',...
    'iqr','sem','std'});



%%%%% Colors setting
col_median = hex2rgb('#000000');
col_quant = hex2rgb('#0033FF');
%%%%% Linetype setting
line_median = '-';
line_q1 = '--';
line_q5 = '-.';
line_q25 = ':';


f1 = figure(1)
f1.WindowState = 'maximized';
plot(stat_grp.Hour,stat_grp.median,'Color',col_median,'LineWidth',4)
hold on
plot(stat_grp.Hour,stat_grp.mean,'Color',col_quant,'LineWidth',4)
plot(stat_grp.Hour,stat_grp.q1,line_q1,'Color',col_quant,...
    'LineWidth',2)
plot(stat_grp.Hour,stat_grp.q99,line_q1,'Color',col_quant,...
    'LineWidth',2,'HandleVisibility','off')
plot(stat_grp.Hour,stat_grp.q5,line_q5,'Color',col_quant,...
    'LineWidth',2)
plot(stat_grp.Hour,stat_grp.q95,line_q5,'Color',col_quant,...
    'LineWidth',2,'HandleVisibility','off')
plot(stat_grp.Hour,stat_grp.q25,line_q25,'Color',col_quant,...
    'LineWidth',2)
plot(stat_grp.Hour,stat_grp.q75,line_q25,'Color',col_quant,...
    'LineWidth',2,'HandleVisibility','off')
xlim([0 23])
xlabel(X_lab)
ylabel(Y_lab)
Lgnd = legend(['Median ' Y_name],['Mean ' Y_name],'1st and 99th percentile',...
    '5th and 95th percentile','25th and 75th percentile',...
    'Location','bestoutside');
Lgnd.FontSize = 14;
t = title(Sup_title);
set(t,'Color','black','fontweight','bold','fontsize',20);
subtitle(Sub_title);

end


